spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 892511315104-djda1nk17f299uvfrau71v4i3suueil6.apps.googleusercontent.com
            client-secret: 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